# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

build:
  os: ubuntu-lts-latest
  tools:
    python: "3.9"
  jobs:
    install:
      - pip install uv
      - uv sync --dev
    build:
      html:
        - uv run sphinx-build -b html docs/ $READTHEDOCS_OUTPUT/html/

# Build documentation in the "docs/" directory with Sphinx
sphinx:
  configuration: docs/conf.py
