---
- include: maven_install.yml
- include: apache_ant_install.yml

- name: download dspace release
  unarchive:
    src: https://github.com/DSpace/DSpace/releases/download/dspace-{{ dspace_version }}/dspace-{{ dspace_version }}-release.zip
    dest: "{{ dspace_source }}"
    remote_src: true
    changed_when: false

- name: create the dspace postgresql database
  postgresql_db:
    name: dspace
    encoding: UTF-8
    lc_collate: en_US.UTF-8
    lc_ctype: en_US.UTF-8

- name: create the dspace postgresql role
  postgresql_user:
    name: dspace
    db: dspace
    encrypted: true
    role_attr_flags: '{{ application_dbuser_role_attr_flags }}'
    state: 'present'

- name: determine if pgcrypto is enabled for PostgreSQL
  shell: psql -c "SELECT extname FROM pg_extension WHERE extname='pgcrypto';" dspace | grep pgcrypto
  register: pg_crypto_enabled

- name: enable the pgcrypto extension for PostgreSQL
  postgresql_query:
    db: dspace
    query: "CREATE EXTENSION pgcrypto;"
    when: not pgcrypto_enabled

- name: create the DSpace configuration file
  template:
    src: 'local.cfg.j2'
    dest: "{{ dspace_source }}/local.cfg"

- name: create the DSpace home directory
  file:
    path: "{{ dspace_home }}"
    state: directory
    mode: '0755'
    owner: dspace
    group: dspace

- name: build the Maven package
  shell:
    chdir: "{{ dspace_source }}"
    cmd: "mvn package"

- name: install DSpace using Ant
  shell:
    chdir: "{{ dspace_source }}/dspace/target/dspace-installer"
    cmd: "ant fresh_install"

- name: create the Tomcat servlet contexts for the DSpace web apps
  template:
    src: 'dspace_app_context.xml.j2'
    dest: "{{ tomcat8_home }}/conf/Catalina/localhost/{{ item }}.xml"
  loop:
    - jspui
    - solr
    - oai
    - rest
    - sword
    - swordv2

- name: create the DSpace admin. account
  shell:
    cmd: "{{ dspace_home }}/bin/dspace create-administrator -e admin@localhost -f Admin -l User -c en_US -p secret"
