---
- include: maven_install.yml
- include: apache_ant_install.yml

- name: create the source directory
  file:
    path: "{{ dspace_source }}"
    state: directory
    mode: "0755"

- name: download dspace release
  unarchive:
    src: https://github.com/DSpace/DSpace/releases/download/dspace-{{ dspace_version }}/dspace-{{ dspace_version }}-release.zip
    dest: "{{ source_directory }}"
    remote_src: true

- name: create the dspace system group
  user:
    name: dspace

- name: create the dspace system user
  user:
    name: dspace
    group: dspace

- name: create the dspace postgresql database
  postgresql_db:
    name: dspace
    encoding: UTF-8
    lc_collate: en_US.UTF-8
    lc_ctype: en_US.UTF-8

- name: create the dspace postgresql role
  postgresql_user:
    name: dspace
    password: dspace
    db: dspace
    encrypted: true
    role_attr_flags: '{{ application_dbuser_role_attr_flags }}'
    state: 'present'

- name: enable the pgcrypto extension for PostgreSQL
  postgresql_query:
    db: dspace
    query: "CREATE EXTENSION pgcrypto;"
  register: pgcrypto_result
  failed_when:
    - pgcrypto_result.rc == 1

- name: create the DSpace configuration file
  template:
    src: 'local.cfg.j2'
    dest: "{{ dspace_source }}/local.cfg"

- name: create the DSpace home directory
  file:
    path: "{{ dspace_home }}"
    state: directory
    mode: '0755'
    owner: dspace
    group: dspace

- name: build the Maven package
  command:
    chdir: "{{ dspace_source }}/dspace"
    cmd: "mvn package"
    creates: "{{ dspace_source }}/dspace/target/dspace-installer"

- name: install DSpace using Ant
  command:
    chdir: "{{ dspace_source }}/dspace/target/dspace-installer"
    cmd: "ant fresh_install"
  register: ant_install
  changed_when:
    - ant_install.rc == 0
  failed_when:
    - ant_install.rc == 1

- name: create the Tomcat servlet contexts for the DSpace web apps
  template:
    src: 'dspace_app_context.xml.j2'
    dest: "{{ tomcat8_home }}/conf/Catalina/localhost/{{ item }}.xml"
  loop:
    - jspui
    - solr
    - oai
    - rest
    - sword
    - swordv2

- name: create the DSpace admin. account
  shell:
    cmd: "{{ dspace_home }}/bin/dspace create-administrator -e admin@localhost -f Admin -l User -c en_US -p secret"
  register: dspace_create_admin
  changed_when:
    - dspace_create_admin.rc == 0
  failed_when:
    - dspace_create_admin.rc == 1
