---
- name: create the Tomcat servlet contexts for the DSpace web apps
  template:
    src: 'dspace_app_context.xml.j2'
    dest: "{{ tomcat8_home }}/conf/Catalina/localhost/{{ item }}.xml"
  loop:
    - jspui
    - solr
    - oai
    - rest
    - sword
    - swordv2

- name: create the DSpace admin. account
  shell:
    cmd: "{{ dspace_home }}/bin/dspace create-administrator -e admin@localhost -f Admin -l User -c en_US -p secret"
