---
- name: ensure tomcat8 packages are installed
  apt:
    name: ["tomcat8"]
    update_cache: true
    state: present

- name: copy tomcat 8 sysv init script
  template:
    src: tomcat8
    dest: /etc/init.d/tomcat8
    owner: tomcat8
    group: tomcat8
  when: not running_on_server

- name: copy tomcat 8 env variable settings
  template:
    src: setenv.sh
    dest: /usr/share/tomcat8/bin/setenv.sh
    owner: tomcat8
    group: tomcat8
  when: not running_on_server

- name: ensure that tomcat8 is started on runlevels 3, 4, and 5
  sysvinit:
    name: tomcat8
    state: started
    enabled: yes
    runlevels:
      - 3
      - 4
      - 5

- name: ensure that tomcat8 is started
  service:
    name: tomcat8
    state: started
    enabled: true
  changed_when: false
  ignore_errors: true
