---
- name: ensure tomcat8 packages are installed
  apt:
    name: ["tomcat8"]
    update_cache: true
    state: present

- name: ensure tomcat8 starts on boot
  service:
    name: tomcat8
    state: started
    enabled: true
  changed_when: false
  ignore_errors: true
  tags:
    - server
