---
- name: copy template config file
  template:
    src: clamd.conf.j2
    dest: "/etc/clamav/clamd.conf"

- name: create and/or update the clamav database
  command: /usr/bin/freshclam --quiet
  args:
    creates: /var/lib/clamav/main.cvd
  changed_when: false
